# Spam Ham Classifier

In [2]:
import pandas as pd

df = pd.read_csv("spam.csv")

df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.groupby('Category').describe()


Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [5]:


df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

df.head()



Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [6]:


from sklearn.model_selection import train_test_split


X_train,X_test,Y_train,Y_test = train_test_split(df.Message,df.spam,test_size=0.20)





In [8]:
X_train.describe()

count                       4457
unique                      4171
top       Sorry, I'll call later
freq                          25
Name: Message, dtype: object

In [9]:
X_test.describe()

count                                                  1115
unique                                                 1093
top       I cant pick the phone right now. Pls send a me...
freq                                                      6
Name: Message, dtype: object

In [11]:
4457+1115


X_train.values

array(['S but mostly not like that.',
       "It is a good thing I'm now getting the connection to bw",
       'Oh just getting even with u.... u?', ...,
       "Yupz... I've oredi booked slots 4 my weekends liao...",
       'We tried to contact you re your reply to our offer of 750 mins 150 textand a new video phone call 08002988890 now or reply for free delivery tomorrow',
       'Anytime lor...'], dtype=object)

In [30]:

from sklearn.feature_extraction.text import CountVectorizer

vizer =  CountVectorizer()


X_train_count= vizer.fit_transform(X_train.values)


print(X_train_count.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [31]:


from sklearn.naive_bayes import MultinomialNB


model = MultinomialNB()


model.fit(X_train_count,Y_train)



MultinomialNB()

In [50]:

emails =["Go until jurong point, crazy.. Available only ...","Free entry in 2 a wkly comp to win FA Cup fina..."]


emails_count = vizer.transform(emails)


res=model.predict(emails_count)


print("Outputs\n")


for i in range(len(res)):
    
    if(res[i]==1):
        ans="spam"
    else:
        ans="ham"
        
    print(emails[i],"  ",ans)

Outputs

Go until jurong point, crazy.. Available only ...    ham
Free entry in 2 a wkly comp to win FA Cup fina...    spam


## Model Performance

In [37]:
X_test_count =  vizer.transform(X_test)


model.score(X_test_count,Y_test)

0.9874439461883409

In [38]:
from sklearn.pipeline import Pipeline

mnb_clf = Pipeline([('vectorizer',CountVectorizer()),('m_nb',MultinomialNB())])

mnb_clf.fit(X_train,Y_train)


Pipeline(steps=[('vectorizer', CountVectorizer()), ('m_nb', MultinomialNB())])

In [40]:
mnb_clf.score(X_test,Y_test)

0.9874439461883409

## Naive Bayes tutorial

In [34]:
'''

import numpy as np
rng = np.random.RandomState(42)
X = rng.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X, y)

print(clf.predict(X[2:3]))


'''

'\n\nimport numpy as np\nrng = np.random.RandomState(42)\nX = rng.randint(5, size=(6, 100))\ny = np.array([1, 2, 3, 4, 5, 6])\nfrom sklearn.naive_bayes import MultinomialNB\nclf = MultinomialNB()\nclf.fit(X, y)\n\nprint(clf.predict(X[2:3]))\n\n\n'

In [27]:
#X[2:3]

array([[1, 2, 0, 0, 3, 2, 4, 2, 3, 3, 2, 3, 2, 1, 2, 2, 3, 3, 0, 0, 1, 0,
        2, 3, 0, 0, 1, 1, 2, 3, 1, 0, 3, 3, 0, 1, 0, 3, 4, 4, 2, 0, 0, 2,
        2, 2, 3, 0, 3, 2, 0, 3, 3, 2, 0, 2, 0, 4, 1, 1, 1, 2, 4, 0, 3, 0,
        3, 0, 4, 3, 2, 0, 0, 3, 2, 2, 4, 2, 2, 2, 1, 4, 0, 3, 0, 4, 3, 4,
        2, 3, 2, 0, 0, 3, 3, 4, 4, 2, 3, 0]])

3